### ISSUE TITLE
Boolean values are converted incorrectly

### ISSUE THREAD

**Issue by giuseppe-santoro** [charto/cxml#1]
All boolean values are converted in true.

The function that convert string 'true' and the string 'false' in boolean is 
`boolean: (function (item) { return !!item; })`

This function returns always true values, in fact
`!!'false'` is equal to true.

A safe alternative should be
`boolean: (function (item) { return item == 'true'; })`

**Comment by jjrv** [comment]
Good point and thank you very much for the PR!

**Comment by giuseppe-santoro** [comment]
Could you please update the npm package?

Thank you
